### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by rwwagner90** [embroider-build/embroider#676]
I am unable to run `ember s` on Windows and get the following error:

```
Error: Cannot find module 'C:Users
wwagDocumentsGitHubswach
ode_modules@embroidercoresrc	emplate-compiler.js'
Require stack:
- $TMPDIR\embroider\af1fbb\_template_compiler_.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\@embroider\hbs-loader\src\index.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\webpack\lib\NormalModule.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\webpack\lib\Compiler.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\webpack\lib\webpack.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\ember-auto-import\js\webpack.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\ember-auto-import\js\bundler.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\ember-auto-import\js\auto-import.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\ember-auto-import\js\index.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\ember-cli\lib\models\package-info-cache\package-info.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\ember-cli\lib\models\package-info-cache\index.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\ember-cli\lib\models\project.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\ember-cli\lib\utilities\get-config.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\ember-cli\lib\utilities\instrumentation.js
- C:\Users\rwwag\Documents\GitHub\swach\node_modules\ember-cli\lib\cli\index.js
- C:\Users\rwwag\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ($TMPDIR\embroider\af1fbb\_template_compiler_.js:1:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.hbsLoader (C:\Users\rwwag\Documents\GitHub\swach\node_modules\@embroider\hbs-loader\src\index.ts:14:66)
  - stack: ModuleBuildError: Module build failed (from C:/Users/rwwag/Documents/GitHub/swach/node_modules/@embroider/hbs-loader/src/index.js):
```

Any ideas how to fix this?

**Comment by rwwagner90** [comment]
It seems like something needs to be updated to handle Windows paths maybe?

**Comment by lifeart** [comment]
looks like issue in `templateCompilerFile`
resolved here: https://github.com/embroider-build/embroider/blob/de2c2d5b94247418409acef9f06d28b1ef4058e3/packages/webpack/src/ember-webpack.ts#L132

**Comment by rwwagner90** [comment]
@lifeart are you saying this should be fixed already? How would I test out the fix?

**Comment by rwwagner90** [comment]
It looks like the latest is already released, so I guess this is still broken?
