### ISSUE TITLE
Embroider safe tests hang for all addons

### ISSUE THREAD

**Issue by rwwagner90** [embroider-build/embroider#827]
I am not sure if this is due to something like ember-cli-addon-docs or what is causing all my addons to hang when I try to add the embroider ember-try scenarios, but I always get `Global error: Uncaught ReferenceError: Ember is not defined`.

Here are a couple builds:

https://github.com/shipshapecode/ember-math-helpers/pull/509
https://github.com/shipshapecode/ember-shepherd/pull/779

@ef4 any ideas here?

**Comment by nlfurniss** [comment]
Maybe the [same issue](https://github.com/embroider-build/embroider/issues/833)?

**Comment by rwwagner90** [comment]
Ah, yes, perhaps. Will wait for a fix to land and see.

**Comment by stefanpenner** [comment]
`Global error: Uncaught ReferenceError: Ember is not defined` should be resolved with https://github.com/emberjs/ember.js/pull/19586.

Your tests don't seem to be failing due to ^ any longer, rather some other issue that at first glance seems like it may not be an issue in embroider rather embroider appears to be providing actionable resolution steps:
```
Build Error (PackagerRunner) in ../../node_modules/ember-modal-dialog/templates/components/modal-dialog.hbs

Module Error (from ../../../../../home/runner/work/ember-shepherd/ember-shepherd/node_modules/thread-loader/dist/cjs.js):
Unsafe dynamic component: this.modalDialogComponentName in $TMPDIR/embroider/1d2fa5/node_modules/ember-modal-dialog/templates/components/modal-dialog.hbs/modal-dialog.hbs
```

I am going to close this issue, but feel free to reopen if I have closed in error.

**Comment by rwwagner90** [comment]
@stefanpenner my tests still fail with `Global error: Uncaught ReferenceError: Ember is not defined` they just hang for hours before you see that message.

**Comment by rwwagner90** [comment]
Here is the error still occurring https://github.com/shipshapecode/ember-shepherd/pull/779/checks?check_run_id=2759690063#step:5:295

Should it be fixed in Ember 3.27.3 or just in canary or how do I test it out?

**Comment by rwwagner90** [comment]
Another failure here https://github.com/shipshapecode/ember-meta/pull/28/checks?check_run_id=2759803987

**Comment by rwjblue** [comment]
@rwwagner90 should have been fixed with ember-source@3.27.3, and tarballs from release + beta + canary channels

**Comment by rwjblue** [comment]
@rwwagner90 - The last link you shared was not anything to do with `Ember is not defined`, the log you linked to shows:

```
not ok 1 Chrome 91.0 - [undefined ms] - Global error: Uncaught Error: an unsupported module was defined, expected `define(id, deps, module)` instead got: `1` arguments to define` at http://localhost:7357/assets/vendor.js, line 67
```

Which is due to a double transpilation of `qunit`. You need to tell the system to skip babeling qunit.

See https://github.com/shipshapecode/ember-meta/pull/28/files#r646644689 for details.

**Comment by rwwagner90** [comment]
@rwjblue Thanks for the help with ember-meta!

I am still experiencing `Ember is not defined` on ember-shepherd. The embroider safe tests run for the max time of 360 minutes, then time out, but if you want for the timeout or cancel, you can see the first few tests are throwing `Ember is not defined`.

**Comment by rwjblue** [comment]
> I am still experiencing Ember is not defined on ember-shepherd.

Ya, I am still debugging that one. It does look like it is using ember-source@3.27.3 (on initial review), so trying to see if it is actually using an old Ember or if somethign else is wrong...

**Comment by mydea** [comment]
FYI, I still get

```
Could not find module `qunit` imported from `(require)`
```

With:

* ember-source 3.27.3
* `@embroider/test-support` 0.41.0

And this code:

```js
  const { maybeEmbroider } = require('@embroider/test-setup');
  return maybeEmbroider(app, {
    skipBabel: [{ package: 'qunit' }],
  });
```

Here: https://github.com/fabscale/ember-layout-components/pull/241/checks?check_run_id=2774322248

**Comment by rwjblue** [comment]
@mydea - Have you debugged? What is importing qunit when the error is thrown?

**Comment by mydea** [comment]
I get this error when installing latest embroider/core & compat & webpack & webpack, run `ember s` and go to `/tests`:

```
Uncaught Error: Could not find module `qunit` imported from `(require)`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at requireModule (loader.js:24)
    at eval (qunit.js:1)
    at Object.../../../externals/qunit.js (chunk.afbb080cb1cb1758f869.js:138)
    at __webpack_require__ (chunk.afbb080cb1cb1758f869.js:162)
    at eval (test-helper.js:4)
    at Object../tests/test-helper.js (chunk.afbb080cb1cb1758f869.js:128)
    at __webpack_require__ (chunk.afbb080cb1cb1758f869.js:162)
    at eval (test.js:215)
tests:57 Uncaught Error: The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js".
    at HTMLDocument.<anonymous> (tests:57)
```

Not sure if that helps?

**Comment by rwjblue** [comment]
@mydea - Ya, I'm mostly asking what code is actually trying to get `qunit` module (e.g. look in the debugger, where the exception is thrown and figure out what package/addon/module/etc is doing it).

**Comment by mydea** [comment]
As far as I can tell it is this line in the (default?) `tests/test-helpers.js` file:

```js
import * as QUnit from 'qunit';
```

**Comment by rwjblue** [comment]
Hmm, @mydea looks like that addon didn't update to latest ember-qunit properly ([docs here](https://github.com/emberjs/ember-qunit/blob/master/docs/migration.md#upgrading-from-v4x-to-v500)), it doesn't have `ember-auto-import` as a devDep (which is the only way `qunit` is ever going to end up in the build). Can you add ember-auto-import and see if that fixes the issue for you?

**Comment by mydea** [comment]
Huh, that worked! I removed ember-auto-import from the dev dependencies as I was not aware it was being used by something in the default blueprint. And since the regular tests worked, I thought that was all good. Weird that this would only fail in embroider then, but in in a regular build :thinking: but thanks a lot for the help!

**Comment by lifeart** [comment]
also related to ember-auto-import - https://github.com/ef4/ember-auto-import/issues/404#issuecomment-857019190
https://github.com/lifeart/ember-click-outside-modifier/pull/5

![image](https://user-images.githubusercontent.com/1360552/121489088-66d2a100-c9dc-11eb-878b-3e65dbb0e1ad.png)

**Comment by lifeart** [comment]
in short, updating addon blueprint with ember-auto-import v2 may cause a lot of issues for addon authors.

**Comment by rwjblue** [comment]
OK, sorry folks. I'm going to close this issue for now. I think there are still valid / active problems that folks are working through, but this issue thread has become a dumping ground of a bunch of different and unrelated (other than that they cause issues) things.

For anyone that is still having issues, please open a new issue dedicated to the specific problem that you are facing. Make sure to include reproduction steps, and a high level summary of your problem.

Again, I'm sorry, but I can't triage all the various problems in the same issue 😞.

**Comment by rwwagner90** [comment]
@rwjblue I seem to still be getting Ember is not defined here https://github.com/shipshapecode/ember-math-helpers/runs/2851158494?check_suite_focus=true

**Comment by ef4** [comment]
@rwwagner90 that is most likely due to https://github.com/embroider-build/embroider/issues/862

**Comment by rwwagner90** [comment]
@ef4 I don't think I am using `window.Ember` anywhere, but I suppose it's possible the testing setup does in some way?

**Comment by ef4** [comment]
@rwwagner90 one of your addons probably is. It looks like this project is using ember-cli-addon-docs, which pulls in quite a lot of stuff. The CI failure you linked to says

> Uncaught ReferenceError: Ember is not defined
